---
openapi: 3.0.3
info:
  title: Quarkus Service API
  description: API surface exposed by the Quarkus service
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://ebanda-dev-liberty-app-ebanda-dev.apps.662f97af563fb9001ea854fa.cloud.techzone.ibm.com/
    description: (RHDH component deployment)
  - url: http://localhost:8080/
    description: (localhost testing)
paths:
  /hello:
    get:
      responses:
        "200":
          description: OK
